# Generated by Django 3.2 on 2021-05-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pp',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/'),
        ),
    ]
